#!/usr/bin/env python3
"""
Minimal splat + matching-build helper bundled with the n64-decomp skill.

Typical layout (override with flags):

  project_root/
    baserom.z64          # or baserom.n64 before create_config
    <game>.yaml
    asm/ bin/ include/  # generated by splat

Commands (run from project_root):

  python references/configure_min.py --status
  python references/configure_min.py --create-config [--rom baserom.n64]
  python references/configure_min.py --split [--yaml game.yaml]
  python references/configure_min.py --emit-configure [--game game]

--emit-configure writes a starter configure.py + build.ninja rules for
assembly-only matching. Adjust VERSION, LD_SCRIPT, and toolchain paths
before expecting a byte match.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

CONFIGURE_PY_TEMPLATE = '''#!/usr/bin/env python3
"""Assembly-only matching build (generated by configure_min.py --emit-configure)."""

import argparse
import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
BUILD_DIR = ROOT / "build"
ASM_DIR = ROOT / "asm"
BASEROM = ROOT / "baserom.z64"
TARGET_ROM = BUILD_DIR / "{game}.z64"
LD_SCRIPT = ROOT / "{game}.ld"  # create from splat or project docs

CC = os.environ.get("CC", "mips-linux-gnu-gcc")
AS = os.environ.get("AS", "mips-linux-gnu-as")
LD = os.environ.get("LD", "mips-linux-gnu-ld")
OBJCOPY = os.environ.get("OBJCOPY", "mips-linux-gnu-objcopy")

CFLAGS = "-G 0 -non_shared -Xfullwarn -x c -O2"
ASFLAGS = "-march=vr4300 -mabi=32 -mno-shared -mno-abicalls"
LDFLAGS = f"-nostdlib -T {{LD_SCRIPT}}"


def asm_objects() -> list[Path]:
    return sorted(ASM_DIR.rglob("*.s"))


def run(cmd: list[str], cwd: Path | None = None) -> None:
    print("[RUN]", " ".join(cmd))
    subprocess.check_call(cmd, cwd=str(cwd or ROOT))


def write_ninja() -> None:
    objs = asm_objects()
    if not objs:
        raise SystemExit(f"No .s files under {{ASM_DIR}} — run splat split first.")

    BUILD_DIR.mkdir(parents=True, exist_ok=True)
    lines = [
        "ninja_required_version = 1.10",
        f"ld_script = {LD_SCRIPT.name}",
        f"target_rom = {TARGET_ROM.name}",
        "",
    ]
    for asm in objs:
        rel = asm.relative_to(ROOT)
        obj = BUILD_DIR / rel.with_suffix(".o")
        lines += [
            f"build {obj}: asm {rel}",
            f"  asm = {AS}",
            f"  asflags = {ASFLAGS}",
            "",
        ]
    obj_paths = " ".join(
        str(BUILD_DIR / o.relative_to(ROOT).with_suffix(".o")) for o in objs
    )
    lines += [
        f"build {TARGET_ROM.name}: link {obj_paths}",
        f"  ld = {LD}",
        f"  ldflags = -nostdlib -T $ld_script",
        "",
        "default $target_rom",
        "",
        "rule asm",
        "  command = $asm $asflags -o $out $in",
        "",
        "rule link",
        "  command = $ld $ldflags -o $out $in",
        "",
    ]
    (ROOT / "build.ninja").write_text("\\n".join(lines), encoding="utf-8")
    print(f"Wrote build.ninja with {{len(objs)}} assembly objects.")


def configure(clean: bool) -> None:
    if clean and BUILD_DIR.exists():
        shutil.rmtree(BUILD_DIR)
    if not LD_SCRIPT.exists():
        raise SystemExit(
            f"Missing linker script {{LD_SCRIPT}}. "
            "Add splat-generated .ld or project linker script first."
        )
    write_ninja()


def build() -> None:
    run(["ninja", "-f", "build.ninja"], cwd=ROOT)


def diff_rom() -> None:
    if not BASEROM.exists():
        raise SystemExit(f"Missing {{BASEROM}}")
    if not TARGET_ROM.exists():
        raise SystemExit(f"Missing built ROM {{TARGET_ROM}} — run --build first.")
    run(["cmp", "-l", str(BASEROM), str(TARGET_ROM)])


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--clean", action="store_true")
    p.add_argument("--build", action="store_true")
    p.add_argument("--diff", action="store_true")
    args = p.parse_args()
    configure(args.clean)
    if args.build:
        build()
    if args.diff:
        diff_rom()


if __name__ == "__main__":
    main()
'''


def repo_root(explicit: Path | None) -> Path:
    return explicit.resolve() if explicit else Path.cwd().resolve()


def rel(path: Path, root: Path) -> str:
    try:
        return str(path.relative_to(root))
    except ValueError:
        return str(path)


def fail(msg: str) -> int:
    print(f"[ERROR] {msg}", file=sys.stderr)
    return 1


def run(cmd: list[str], cwd: Path) -> int:
    print(f"[RUN] ({cwd}) {' '.join(cmd)}")
    return subprocess.run(cmd, cwd=str(cwd)).returncode


def detect_yaml(root: Path, yaml_dir: Path, yaml_arg: str | None) -> Path | None:
    if yaml_arg:
        p = yaml_dir / yaml_arg
        return p if p.exists() else None
    yamls = sorted(yaml_dir.glob("*.yaml"))
    return yamls[0] if yamls else None


def find_rom(root: Path, rom_arg: str | None) -> Path:
    if rom_arg:
        p = root / rom_arg
        return p
    for name in ("baserom.z64", "baserom.n64", "baserom.v64"):
        p = root / name
        if p.exists():
            return p
    return root / "baserom.z64"


def cmd_status(root: Path, rom: Path, yaml_dir: Path) -> int:
    yaml_path = detect_yaml(root, yaml_dir, None)
    print("[STATUS] configure_min.py")
    print(f"  root:      {root}")
    print(f"  rom:       {rel(rom, root)} ({'ok' if rom.exists() else 'missing'})")
    print(f"  yaml_dir:  {rel(yaml_dir, root)}")
    print(f"  yaml:      {rel(yaml_path, root) if yaml_path else '(none)'}")
    print(f"  asm/:      {'ok' if (root / 'asm').is_dir() else 'missing (run --split)'}")
    script = Path(__file__).resolve()
    print(f"  script:    {script}")
    return 0


def cmd_create_config(root: Path, rom: Path) -> int:
    if not rom.exists():
        return fail(f"ROM not found: {rel(rom, root)}")
    if shutil.which("uv") is None:
        return fail("`uv` not on PATH — install uv or run splat manually.")
    return run(["uv", "run", "-m", "splat", "create_config", rom.name], cwd=root)


def cmd_split(root: Path, yaml_dir: Path, yaml_arg: str | None) -> int:
    yaml_path = detect_yaml(root, yaml_dir, yaml_arg)
    if yaml_path is None:
        return fail(f"No YAML in {rel(yaml_dir, root)} — run --create-config first.")
    if shutil.which("uv") is None:
        return fail("`uv` not on PATH.")
    return run(
        ["uv", "run", "-m", "splat", "split", yaml_path.name],
        cwd=yaml_dir if yaml_dir != root else root,
    )


def cmd_emit_configure(root: Path, game: str) -> int:
    out = root / "configure.py"
    if out.exists():
        print(f"[WARN] {rel(out, root)} already exists — not overwriting.")
        return 0
    text = CONFIGURE_PY_TEMPLATE.format(game=game)
    out.write_text(text, encoding="utf-8")
    try:
        out.chmod(out.stat().st_mode | 0o111)
    except OSError:
        pass
    print(f"Wrote {rel(out, root)} (assembly-only starter).")
    print("Next: add linker script, fix toolchain env vars, then:")
    print("  python configure.py --clean && python configure.py --build")
    return 0


def cmd_wsl_preflight() -> int:
    if shutil.which("wsl.exe") is None:
        return fail("`wsl.exe` not on PATH (Windows only).")
    script = (
        "set -e; "
        "echo '=== WSL MIPS precheck ==='; "
        "for t in mips-linux-gnu-as mips-linux-gnu-ld mips-linux-gnu-objdump "
        "mips-linux-gnu-readelf python3 make; do "
        "command -v \"$t\" >/dev/null || { echo \"missing: $t\"; exit 1; }; "
        "done; "
        "mips-linux-gnu-as --version | head -n1; "
        "python3 --version"
    )
    return run(["wsl.exe", "-e", "bash", "-lc", script], cwd=Path.cwd())


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--root", type=Path, default=None, help="Decomp project root (default: cwd)")
    p.add_argument("--rom", default=None, help="ROM path relative to root")
    p.add_argument("--yaml-dir", default=None, help="Directory containing splat yaml (default: root)")
    p.add_argument("--yaml", default=None, help="YAML filename for --split")
    p.add_argument("--game", default="game", help="Game slug for --emit-configure")
    p.add_argument("--status", action="store_true")
    p.add_argument("--create-config", action="store_true")
    p.add_argument("--split", action="store_true")
    p.add_argument("--emit-configure", action="store_true")
    p.add_argument("--wsl-preflight", action="store_true")
    return p.parse_args()


def main() -> int:
    args = parse_args()
    root = repo_root(args.root)
    yaml_dir = root / (args.yaml_dir or ".")
    yaml_dir = yaml_dir.resolve()
    rom = find_rom(root, args.rom)

    if not args.status and not args.create_config and not args.split and not args.emit_configure and not args.wsl_preflight:
        return cmd_status(root, rom, yaml_dir)

    code = 0
    if args.status:
        code = cmd_status(root, rom, yaml_dir) or code
    if args.create_config:
        code = cmd_create_config(root, rom) or code
    if args.split:
        code = cmd_split(root, yaml_dir, args.yaml) or code
    if args.emit_configure:
        code = cmd_emit_configure(root, args.game) or code
    if args.wsl_preflight:
        code = cmd_wsl_preflight() or code
    return code


if __name__ == "__main__":
    sys.exit(main())
